language: php
php:
    - '7.0'
    - '7.1'

env:
    - SYMFONY_VERSION="dev-master" DB=mysql

script: phpunit -c app

notifications:
    slack: ouloulouteam:4F2CdbA3tQcHvyoczPoh9lcK
    on_success: always
    on_failure: always