language: php
php:
    - '5.6'
    - '7.0'
    - '7.1'
services:
    - mysql
env:
    - SYMFONY_VERSION="3.1.*" DB=mysql
before_script:
    - mysql -e 'create database symfony;'
    - composer install
    - php bin/console doctrine:schema:create --env=test
    #- php bin/console hautelook_alice:doctrine:fixtures:load -n --env=test

script:
    - phpunit --configuration phpunit.xml.dist --coverage-text
    - phpunit --coverage-clover=coverage.xml

notifications:
    slack: ouloulouteam:4F2CdbA3tQcHvyoczPoh9lcK
    on_success: always
    on_failure: always

after_success:
    - bash <(curl --data-binary @codecov.yml https://codecov.io/validate)