<?php

namespace AppBundle\Repository;

/**
 * PcRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PcRepository extends \Doctrine\ORM\EntityRepository
{
}
